-- Create the table for storing property analysis logs
CREATE TABLE IF NOT EXISTS property_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT, -- Can be null if anonymous
    address TEXT NOT NULL,
    analysis_result JSONB, -- Stores the JSON output from the LLM
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Recommended: Create an index on address for faster lookups
CREATE INDEX IF NOT EXISTS idx_property_logs_address ON property_logs(address);

-- Optional: Create an index on created_at for cleanup/time-based queries
CREATE INDEX IF NOT EXISTS idx_property_logs_created_at ON property_logs(created_at);

-- [NEW] User Preferences Table
CREATE TABLE IF NOT EXISTS user_preferences (
    user_email TEXT PRIMARY KEY,
    preference_summary TEXT, -- Stores the "refined rules" as text
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- [NEW] User Ratings Table
CREATE TABLE IF NOT EXISTS user_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    context TEXT, -- e.g., "Page: Property Analysis" or "Address: 123 Main St"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- --- RLS POLICIES ---
-- Enable RLS on tables (Best practice, though we will set permissive policies here since Streamlit handles auth)

-- 1. User Preferences
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;

-- Allow anyone with the API key to Select/Insert/Update (The Streamlit app controls the logic)
CREATE POLICY "Allow public access to preferences"
ON user_preferences
FOR ALL
USING (true)
WITH CHECK (true);

-- 2. User Ratings
ALTER TABLE user_ratings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access to ratings"
ON user_ratings
FOR ALL
USING (true)
WITH CHECK (true);

-- 3. Property Logs
ALTER TABLE property_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access to logs"
ON property_logs
FOR ALL
USING (true)
WITH CHECK (true);

